# Generated by Django 5.2.16 on 2026-07-18 19:19

import django.db.models.deletion
from django.db import migrations, models


def schepen_overzetten(apps, schema_editor):
    """Het schip dat in het profiel stond wordt het eerste (actieve) schip."""
    Piloot = apps.get_model("corphauling", "Piloot")
    Schip = apps.get_model("corphauling", "Schip")
    for piloot in Piloot.objects.all():
        Schip.objects.create(
            piloot=piloot,
            schip_type_id=piloot.schip_type_id,
            fit=piloot.fit,
            hold_handmatig=piloot.hold_handmatig,
            actief=True,
        )


def schepen_terugzetten(apps, schema_editor):
    """Terugweg: het actieve schip weer op het profiel zetten."""
    Piloot = apps.get_model("corphauling", "Piloot")
    for piloot in Piloot.objects.all():
        schip = piloot.schepen.filter(actief=True).first() or piloot.schepen.first()
        if schip:
            piloot.schip_type_id = schip.schip_type_id
            piloot.fit = schip.fit
            piloot.hold_handmatig = schip.hold_handmatig
            piloot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('corphauling', '0002_piloot_fit_piloot_hold_handmatig_piloot_jf_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schip_type_id', models.IntegerField(choices=[(28850, 'Ark (Amarr)'), (28848, 'Anshar (Gallente)'), (28846, 'Nomad (Minmatar)'), (28844, 'Rhea (Caldari)')], default=28850, help_text='Bepaalt het isotopenverbruik, de brandstofsoort en hoeveel er in past.', verbose_name='Schip')),
                ('naam', models.CharField(blank=True, default='', help_text='Optioneel, bijvoorbeeld "grote hauler" — handig als je er meerdere hebt.', max_length=60, verbose_name='Eigen naam')),
                ('fit', models.TextField(blank=True, default='', help_text='Plak je fit zoals je die in EVE kopieert. Modules die de vrachtruimte vergroten tellen mee, mét stacking-penalty. Leeg = kale romp.', verbose_name='Fit (plakken uit EVE)')),
                ('hold_handmatig', models.FloatField(default=0, help_text='0 = uitrekenen uit schip, skills en fit. Vul het getal uit de game in als je zeker wilt weten dat het klopt — dat gaat altijd voor.', verbose_name='Vrachtruimte zelf invullen (m³)')),
                ('actief', models.BooleanField(default=False, help_text='Met dit schip wordt op het contractenbord gerekend.', verbose_name='Actief')),
                ('piloot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schepen', to='corphauling.piloot')),
            ],
            options={
                'verbose_name': 'schip',
                'verbose_name_plural': 'schepen',
                'ordering': ('-actief', 'id'),
                'default_permissions': (),
            },
        ),
        # Eerst de bestaande gegevens overzetten, pas daarna de oude velden weg.
        migrations.RunPython(schepen_overzetten, schepen_terugzetten),
        migrations.RemoveField(model_name="piloot", name="fit"),
        migrations.RemoveField(model_name="piloot", name="hold_handmatig"),
        migrations.RemoveField(model_name="piloot", name="schip_type_id"),
    ]
