# Generated by Django 5.2.16 on 2026-07-18 20:03

import django.db.models.deletion
from django.db import migrations, models


def fits_koppelen(apps, schema_editor):
    """Bestaande schepen aan de corp-fit van hun romp hangen."""
    Schip = apps.get_model("corphauling", "Schip")
    CorpFit = apps.get_model("corphauling", "CorpFit")
    for schip in Schip.objects.filter(corp_fit__isnull=True):
        fit = CorpFit.objects.filter(schip_type_id=schip.schip_type_id).order_by(
            "volgorde", "naam").first()
        if fit:
            schip.corp_fit = fit
            schip.save(update_fields=["corp_fit"])


def fits_loskoppelen(apps, schema_editor):
    """Terugweg: de fit-tekst terugzetten in het losse veld."""
    Schip = apps.get_model("corphauling", "Schip")
    for schip in Schip.objects.exclude(corp_fit__isnull=True):
        schip.fit = schip.corp_fit.fit
        schip.corp_fit = None
        schip.save(update_fields=["fit", "corp_fit"])


class Migration(migrations.Migration):

    dependencies = [
        ('corphauling', '0005_remove_piloot_jdc_remove_piloot_jf_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schip',
            name='hold_handmatig',
        ),
        migrations.AddField(
            model_name='schip',
            name='corp_fit',
            field=models.ForeignKey(blank=True, help_text='De corp-fit waarmee dit schip vliegt. Past de corp de fit aan, dan telt dat hier meteen mee.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schepen', to='corphauling.corpfit', verbose_name='Fit'),
        ),
        migrations.AlterField(
            model_name='schip',
            name='fit',
            field=models.TextField(blank=True, default='', editable=False, help_text='Losse fit-tekst; alleen nog voor schepen van vóór de corp-fits.'),
        ),
    
        migrations.RunPython(fits_koppelen, fits_loskoppelen),
    ]
