# Generated by Django 5.2.16 on 2026-07-19 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corphauling', '0007_delete_config_remove_schip_corp_fit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.BigIntegerField(unique=True)),
                ('character_id', models.BigIntegerField()),
                ('character_name', models.CharField(default='', max_length=100)),
                ('reward', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('collateral', models.FloatField(default=0)),
                ('start_name', models.CharField(default='', max_length=120)),
                ('end_name', models.CharField(default='', max_length=120)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('failed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corphauling_hauls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_completed',),
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'date_completed'], name='corphauling_user_id_3c7d33_idx')],
            },
        ),
    ]
